# 参考: http://t-wada.hatenablog.jp/entry/mac-provisioning-by-ansible
- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  vars:
    homebrew_taps: []
    # FIXME: ansible 2.7でもとに戻す
    # homebrew_taps:
    #   - homebrew/binary
    #   - homebrew/dupes
    #   - caskroom/cask
    homebrew_packages:
      - { name: ansible }
      - { name: autoconf }
      - { name: automake }
      - { name: coreutils }
      - { name: curl }
      - { name: gdbm }
      - { name: git }
      - { name: kubectl }
      - { name: libyaml }
      - { name: mariadb }
      - { name: mosh }
      - { name: nvim }
      - { name: openssl }
      - { name: openssl, state: linked, install_options: force }
      - { name: pcre }
      - { name: peco }
      - { name: pkg-config }
      - { name: python }
      # brewじゃなくて手動で入れる(dotfilesの内容をmac依存にしないため)
      # - { name: rbenv }
      - { name: readline }
      - { name: redis }
      # brewじゃなくて手動で入れる(dotfilesの内容をmac依存にしないため)
      # - { name: ruby-build }
      - { name: screen }
      - { name: sqlite, install_options: force }
      - { name: ssh-copy-id }
      - { name: subversion }
      - { name: the_silver_searcher }
      - { name: tree }
      - { name: vim }
      - { name: watch }
      - { name: wget }
      - { name: zsh }
      - { name: jq }
      - { name: npm }
      - { name: htop }
      - { name: packer }
    homebrew_cask_packages:
      - { name: adobe-reader }
      - { name: docker }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-cloud-sdk }
      - { name: google-japanese-ime }
      - { name: hyperswitch }
      - { name: iterm2 }
      - { name: java }
      - { name: kindle }
      - { name: limechat }
      - { name: skitch }
      - { name: skype }
      - { name: slack }
      - { name: sourcetree }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: xquartz }
  tasks:
    - name: homebrew の tap リポジトリを追加
      homebrew_tap: tap={{ item }} state=present
      with_items: "{{ homebrew_taps }}"

    - name: homebrew をアップデート
      homebrew: update_homebrew=yes

    # brew
    - name: brew パッケージをインストール
      homebrew: >
        name={{ item.name }}
        state={{ item.state | default('latest') }}
        install_options={{
          item.install_options | default() | join(',')
          if item.install_options is not string
          else item.install_options
        }}
      with_items: "{{ homebrew_packages }}"
      register: brew_result
    - name: brew パッケージの情報保存先ディレクトリを作成
      file: path=brew_info state=directory
    - name: brew パッケージの情報を保存
      shell: brew info {{ item }} > brew_info/{{ item }}
      with_items: "{{ brew_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

    # cask
    - name: cask パッケージをインストール
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: "{{ homebrew_cask_packages }}"
      register: cask_result
    - name: cask パッケージの情報保存先ディレクトリを作成
      file: path=cask_info state=directory
    - name: cask パッケージの情報を保存
      shell: brew cask info {{ item }} > cask_info/{{ item }}
      with_items: "{{ cask_result.results | selectattr('changed') | map(attribute='item') | map(attribute='name') | list }}"

    # oh-my-zsh
    - name: oh-my-zsh のインストール
      shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
      args:
        creates: ~/.oh-my-zsh/
